import dever from "../assets/img/icons/projects/DEVER.svg";
import contactImg from "../assets/img/icons/projects/contact.png";
import console from "../assets/img/icons/console.png";
import appIcon from "../assets/img/icons/appStore.png";
import sevexchange from "../assets/img/icons/projects/sevexchange.png";

import AppStore from "../components/specific/portfolio/wndows/AppStore";
import Contact from "../components/specific/portfolio/wndows/Contact";
import Terminal from "../components/specific/portfolio/wndows/Terminal";
import Skills from "../components/specific/portfolio/wndows/Skills";
import Career from "../components/specific/portfolio/wndows/Career";
import Vault from "../components/specific/portfolio/wndows/Vault";
import Bot from "../components/specific/portfolio/wndows/Bot";
import { appWindow } from "../components/specific/portfolio/wndows/AppWindow";
import { L } from "./i18n";

const MTN_LOGO = "https://my.mtn.bj/wp-content/themes/kamgoko/mtn-logo-nav-new.svg";
const KAMGOKO = "KAMGOKO Technologies";
const STUDIO = "Fidèle SODOGA · Fresnel AGLOSSI";

/* Company / theme folders (iOS-style groups). Apps carrying `group` are folded here. */
export const groupsMeta = {
  Apps: { name: "Apps", icon: "/icons/ph/squares-four__ffffff.svg", bg: "#1a1033" },
  MTN: { name: "MTN", icon: MTN_LOGO, bg: "#FFFFFF" },
  Trainings: { name: "Trainings", icon: "/icons/ph/graduation-cap__ffffff.svg", bg: "#0e0730" },
};

export const performances = [
  /* ============ System apps (Paul's mind) ============ */
  {
    id: "career",
    icon: "/icons/ph/briefcase__ffffff.svg",
    bg: "#4a34d6",
    label: "Career",
    group: "Apps",
    get content() { return <Career />; },
    properties: {
      category: L("System · Experience", "Système · Expérience"),
      status: "Live",
      role: L("Full-Stack Software Engineer", "Ingénieur logiciel full-stack"),
      year: "2020 — Present",
      stack: ["React JS"],
      features: [L("5+ years of experience", "Plus de 5 ans d'expérience"), L("Interactive timeline", "Frise interactive"), "Data source: experiences.js"],
      more: L("5+ years of professional experience rendered as a live, data-driven timeline.", "Plus de 5 ans d'expérience professionnelle sous forme de frise dynamique."),
    },
  },
  {
    id: "skills",
    icon: "/icons/ph/brain__ffffff.svg",
    bg: "#d98400",
    label: "Skills",
    group: "Apps",
    get content() { return <Skills />; },
    properties: {
      category: L("System · Stack", "Système · Stack"),
      status: "Live",
      role: "Full-Stack",
      year: "Today",
      stack: ["React JS"],
      features: [L("8 skill categories", "8 catégories de compétences"), L("Proficiency bars", "Barres de niveau"), "Data source: skillset.js"],
      more: L("The technical stack running on this machine, with proficiency levels.", "La stack technique qui tourne sur cette machine, avec les niveaux."),
    },
  },
  {
    id: "bot",
    icon: "/icons/ph/robot__ffffff.svg",
    bg: "#7846dc",
    label: "PaulBot",
    get content() { return <Bot />; },
    properties: {
      category: L("System · AI assistant", "Système · Assistant IA"),
      status: "Live",
      role: L("Portfolio assistant", "Assistant du portfolio"),
      year: "Today",
      stack: ["Next.js", "Groq / Ollama", "Llama 3.3"],
      features: [L("Answers about Paul", "Répond à propos de Paul"), L("Streaming replies", "Réponses en streaming"), L("Context-stuffed, RAG-ready", "Context-stuffing, prêt pour le RAG")],
      more: L("A chat assistant grounded in Paul's real data (CV, projects, skills). Swappable engine — Groq now, self-hosted Ollama later.", "Un assistant de chat nourri des vraies données de Paul (CV, projets, compétences). Moteur interchangeable — Groq maintenant, Ollama auto-hébergé plus tard."),
    },
  },
  {
    id: "vault",
    icon: "/icons/ph/lock-key__ffffff.svg",
    bg: "#2a1f5c",
    label: "Enterprise",
    group: "Apps",
    get content() { return <Vault />; },
    properties: {
      category: L("System · Confidential", "Système · Confidentiel"),
      status: "Enterprise",
      year: "2022 — 2026",
      stack: ["React JS"],
      features: [L("Private & enterprise projects", "Projets privés & entreprise"), L("Described with permission", "Décrits avec autorisation")],
      more: L("Private & enterprise engagements — companies disclosed, project details under NDA.", "Prestations privées & entreprise — entreprises communiquées, détails des projets sous NDA."),
    },
  },
  {
    id: "cv",
    icon: "/icons/ph/file-text__ffffff.svg",
    bg: "#0e7c66",
    label: "CV",
    isLink: true,
    embed: true,
    fullscreenOnly: true,
    syncLang: true,
    url: "/cv",
    get content() { return appWindow(this); },
    properties: {
      category: L("System · Résumé", "Système · CV"),
      status: "Live",
      role: L("Full-Stack Software Engineer", "Ingénieur logiciel full-stack"),
      year: "2020 — Present",
      stack: ["HTML", "CSS", "JavaScript"],
      features: [L("FR / EN + 4 profiles", "FR / EN + 4 profils"), L("One-click PDF export", "Export PDF en un clic"), L("Always fullscreen", "Toujours en plein écran")],
      more: L("My interactive résumé — bilingual, with Full-Stack / Frontend / Backend / DevOps variants and PDF export.", "Mon CV interactif — bilingue, avec les variantes Full-Stack / Frontend / Backend / DevOps et export PDF."),
    },
  },

  /* ============ Featured public app ============ */
  {
    id: "emilia",
    icon: "https://emiliacross.com/assets/images/app-logo-rounded.png",
    bg: "#00000000",
    label: "Emilia Cross",
    isLink: true,
    embed: false,
    url: "https://emiliacross.com/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Dating app (Flutter + PWA) · per-minute video", "App de rencontre (Flutter + PWA) · visio facturée"),
      status: "Live",
      role: L("Full-stack & real-time engineer (Flutter + NestJS)", "Ingénieur full-stack & temps réel (Flutter + NestJS)"),
      client: "France Assist",
      team: "France Assist",
      collaboraters: "Clavers (design) · Fresnel Aglossi (front back-office)",
      year: "2024 — 2025",
      stack: ["Flutter", "Vue.js", "NestJS", "TypeScript", "PostgreSQL", "Socket.io", "Agora RTC", "Stripe", "Firebase", "Docker"],
      features: [
        L("Flutter mobile app + PWA clients", "Clients Flutter : app mobile + PWA"),
        L("Per-minute credit-based billing (Stripe)", "Facturation à la minute par crédits (Stripe)"),
        L("Agora live video + dedicated WebSocket signaling", "Vidéo live Agora + signalisation WebSocket dédiée"),
        L("KYC (Stripe Identity), fine-grained RBAC and 2FA", "KYC (Stripe Identity), RBAC granulaire et 2FA"),
        L("Referral program with native & PWA deep links", "Système de parrainage avec deep links (natif & PWA)"),
        L("Admin BI dashboard (Vue.js) — KPIs via single-query SQL aggregates", "Back-office BI (Vue.js) — KPIs via agrégats SQL en un seul query"),
      ],
      createdAt: "January 2024",
      addedAt: "Today",
      more: L(
        "A dating app (Flutter mobile + PWA) where connections are made over live video billed per minute: Agora video, credit system, KYC verification (Stripe Identity), Stripe payments & payouts, partner discovery and real-time messaging. Multi-service NestJS backend with a dedicated WebSocket server, RBAC, 2FA and monitoring. It also ships a referral program (native & PWA deep links) and a Vue.js BI back-office: each influencer's KPIs — referrals, 30/7-day signups, active accounts, verified KYC, blocked/banned — are computed in a single SQL aggregate query, exposed through permission-gated, privacy-safe endpoints (no sensitive data ever leaves the API).",
        "Une application de rencontre (Flutter mobile + PWA) où la relation se noue en visio facturée à la minute : vidéo Agora, système de crédits, vérification d'identité (Stripe Identity/KYC), paiements & reversements (payouts) Stripe, découverte de partenaires et messagerie temps réel. Backend NestJS multi-services avec serveur WebSocket dédié, RBAC, 2FA et supervision. Elle embarque aussi un système de parrainage (deep links natif & PWA) et un back-office BI en Vue.js : les KPIs de chaque influenceur — filleuls, inscriptions 30/7 jours, comptes actifs, KYC vérifiés, bloqués/bannis — sont calculés en un seul query d'agrégats SQL, exposés via des endpoints gatés par permission et à projection sûre (aucune donnée sensible ne sort de l'API)."
      ),
    },
  },

  /* ============ Personal apps & demos ============ */
  {
    id: "dever",
    icon: dever.src,
    label: "My Blog",
    isLink: true,
    embed: true, // iframe direct du blog dans l'OS (même origine → autorisé par frame-src 'self')
    url: "/blog",
    get content() { return appWindow(this); },
    properties: {
      category: L("Personal · Blog", "Personnel · Blog"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      year: "2021 — Present",
      stack: ["Next.js", "React", "SSG"],
      features: [L("Bilingual articles (FR/EN)", "Articles bilingues (FR/EN)"), L("Search, RSS & listen mode", "Recherche, RSS & mode écoute")],
      createdAt: "December 15, 2021",
      addedAt: "October 20, 2022",
      more: L("Where I share my work, experiments and news — now built into this portfolio.", "Où je partage mon travail, mes expériences et mes actus — désormais intégré à ce portfolio."),
    },
  },
  {
    id: "terminal",
    icon: console.src,
    label: "Terminal",
    group: "Apps",
    bg: "#00000000",
    content: <Terminal />,
    properties: {
      category: L("System · Shell", "Système · Shell"),
      status: "Live",
      role: "React JS",
      year: "2022",
      stack: ["React JS"],
      features: [L("about · edu · skills commands", "commandes about · edu · skills"), L("Interactive CLI", "CLI interactive")],
      more: L("Discover information about me by typing commands.", "Découvrez des infos sur moi en tapant des commandes."),
    },
  },
  {
    id: "contact",
    icon: contactImg.src,
    label: "Contact me",
    get content() { return <Contact />; },
    properties: {
      category: L("System · Contact", "Système · Contact"),
      status: "Live",
      role: "Next JS",
      year: "2022",
      stack: ["Next.js"],
      features: [L("Message form", "Formulaire de message"), L("Direct reach", "Contact direct")],
      more: L("Reach me directly through the form.", "Contactez-moi directement via le formulaire."),
    },
  },
  {
    id: "appStore",
    icon: appIcon.src,
    bg: "#999",
    label: "App Store",
    group: "Apps",
    get content() { return <AppStore />; },
    properties: {
      category: L("Mobile · Store", "Mobile · Store"),
      status: "Live",
      role: L("Mobile Developer", "Développeur mobile"),
      year: "2024 — 2025",
      stack: ["Flutter", "Dart", "NestJS"],
      features: ["Emilia Cross · InvoicePay", L("Flutter apps", "Applis Flutter")],
      more: L("My mobile projects built with Flutter.", "Mes projets mobiles réalisés avec Flutter."),
    },
  },

  /* ============ MTN group (company folder) ============ */
  {
    id: "yconnect",
    icon: MTN_LOGO,
    label: "Y'ello Connect",
    bg: "#FFFFFF",
    group: "MTN",
    isLink: true,
    embed: false,
    url: "https://auth.mtn.bj/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Telecom · Auth / SSO", "Télécom · Auth / SSO"),
      status: "Live",
      role: L("Frontend Developer", "Développeur frontend"),
      client: "MTN Bénin · via KAMGOKO",
      team: KAMGOKO,
      year: "2024",
      stack: ["Vue.js", "Bootstrap", "Node.js"],
      features: [L("Single sign-on portal", "Portail d'authentification unique"), L("Secure authentication", "Authentification sécurisée")],
      more: L("Y'ello Connect — MTN Bénin's authentication portal.", "Y'ello Connect — le portail d'authentification de MTN Bénin."),
    },
  },
  {
    id: "mtnselfcare",
    icon: MTN_LOGO,
    label: "My MTN Web",
    bg: "#FFFFFF",
    group: "MTN",
    isLink: true,
    embed: false,
    url: "https://my.mtn.bj/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Telecom · Selfcare", "Télécom · Selfcare"),
      status: "Live",
      role: L("Frontend Developer", "Développeur frontend"),
      client: "MTN Bénin · via KAMGOKO",
      team: KAMGOKO,
      year: "2024",
      stack: ["Vue.js", "WordPress", "Bootstrap", "Node.js"],
      features: [L("Plans, purchases & account", "Forfaits, achats & compte"), L("RESTful API integration", "Intégration d'APIs RESTful"), L("Advanced state management", "Gestion d'état avancée")],
      more: L("MyMTN Web — all of MTN in a single self-service application.", "MyMTN Web — tout MTN dans une seule application self-service."),
    },
  },
  {
    id: "monrouteur",
    icon: MTN_LOGO,
    label: "Mon routeur",
    bg: "#FFFFFF",
    group: "MTN",
    isLink: true,
    embed: false,
    url: "https://monrouteur.mtn.bj/?ref=noref",
    get content() { return appWindow(this); },
    properties: {
      category: L("Telecom · Activation", "Télécom · Activation"),
      status: "Live",
      role: L("Frontend Developer", "Développeur frontend"),
      client: "MTN Bénin · via KAMGOKO",
      team: KAMGOKO,
      year: "2024",
      stack: ["HTML", "CSS", "JS", "Nginx"],
      features: [L("Zero-balance landing", "Landing solde épuisé"), L("Plan/data activation", "Activation forfait/data")],
      more: L("MonRouteur — activation landing shown when an MTN router runs out of plan or data.", "MonRouteur — page d'activation affichée quand un routeur MTN n'a plus de forfait ou de data."),
    },
  },
  {
    id: "ytickets",
    icon: MTN_LOGO,
    label: "Y'ello Tickets",
    bg: "#FFFFFF",
    group: "MTN",
    isLink: true,
    embed: false,
    url: "https://my.mtn.bj/yello-tickets/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Telecom · Support", "Télécom · Support"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      client: "MTN Bénin · via KAMGOKO",
      team: KAMGOKO,
      year: "2024",
      stack: ["Vue.js", "Node.js"],
      features: [L("Agent ticket management", "Gestion des tickets par agents"), L("Support workflow", "Workflow de support")],
      more: L("Support-ticket management used by MTN agents.", "Gestion des tickets de support utilisée par les agents MTN."),
    },
  },
  {
    id: "ymarket",
    icon: MTN_LOGO,
    label: "Y'ello Market",
    bg: "#FFFFFF",
    group: "MTN",
    isLink: true,
    embed: false,
    url: "https://shop.mtn.bj/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Telecom · E-commerce", "Télécom · E-commerce"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      client: "MTN Bénin · via KAMGOKO",
      team: KAMGOKO,
      year: "2024",
      stack: ["Vue.js", "Node.js"],
      features: [L("Online marketplace", "Marketplace en ligne"), L("Buy & sell in Benin", "Achat & vente au Bénin")],
      more: L("Online marketplace for all kinds of products in Benin.", "Marketplace en ligne pour tous types de produits au Bénin."),
    },
  },
  {
    id: "mtnbj",
    icon: MTN_LOGO,
    label: "MTN Bénin",
    bg: "#FFFFFF",
    group: "MTN",
    isLink: true,
    embed: false,
    url: "https://www.mtn.bj/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Telecom · Corporate", "Télécom · Corporate"),
      status: "Live",
      role: L("WordPress Developer", "Développeur WordPress"),
      client: "MTN Bénin · via KAMGOKO",
      team: KAMGOKO,
      year: "2022 — 2025",
      stack: ["WordPress", "PHP", "SASS"],
      features: [L("Custom theme & plugins", "Thème & plugins sur mesure"), L("Performance & SEO", "Performance & SEO")],
      more: L("Corporate website of MTN Bénin — custom WordPress theme and plugins.", "Site corporate de MTN Bénin — thème et plugins WordPress sur mesure."),
    },
  },
  {
    id: "mtncg",
    icon: MTN_LOGO,
    label: "MTN Congo",
    bg: "#FFFFFF",
    group: "MTN",
    isLink: true,
    embed: false,
    url: "http://mtn.cg/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Telecom · Corporate", "Télécom · Corporate"),
      status: "Live",
      role: L("WordPress Developer", "Développeur WordPress"),
      client: "MTN Congo",
      team: KAMGOKO,
      year: "2022 — 2025",
      stack: ["WordPress", "PHP", "SASS"],
      features: [L("Custom theme & plugins", "Thème & plugins sur mesure"), L("Multilingual content", "Contenu multilingue")],
      more: L("Corporate website of MTN Congo — custom WordPress theme and plugins.", "Site corporate de MTN Congo — thème et plugins WordPress sur mesure."),
    },
  },

  /* ============ Other apps & collaborations ============ */
  {
    id: "avcall",
    icon: "/icons/ph/users-three__4a34d6.svg",
    bg: "#fff",
    label: "AV Call",
    group: "Trainings",
    isLink: true,
    embed: true,
    url: "https://avcall.netlify.app",
    get content() { return appWindow(this); },
    properties: {
      category: L("Training · Meeting", "Formation · Visio"),
      status: "Training",
      role: L("Frontend Developer", "Développeur frontend"),
      year: "2023",
      stack: ["React JS", "WebRTC"],
      features: [L("One-click meetings", "Réunions en un clic"), L("Audio & video call", "Appel audio & vidéo")],
      more: L("Quick audio & video meetings in one click.", "Réunions audio & vidéo rapides en un clic."),
    },
  },
  {
    id: "wecard",
    icon: "https://wecard-dever.netlify.app/card.png",
    bg: "#333333",
    label: "WeCard",
    group: "Trainings",
    isLink: true,
    embed: true,
    url: "https://wecard-dever.netlify.app",
    get content() { return appWindow(this); },
    properties: {
      category: L("Training · Virtual card", "Formation · Carte virtuelle"),
      status: "Training",
      role: L("Frontend Developer", "Développeur frontend"),
      year: "2019",
      stack: ["Vue.js"],
      features: [L("Generate a virtual card", "Générer une carte virtuelle"), L("Export as image", "Export en image")],
      more: L("Generate your virtual credit card and export everything as an image.", "Générez votre carte de crédit virtuelle et exportez le tout en image."),
    },
  },
  {
    id: "jenny",
    icon: "https://jennyfer-portfolio.netlify.app/img/fav.jpg",
    bg: "#ffffff",
    label: "Jenny Portfolio",
    isLink: true,
    embed: true,
    url: "https://jennyfer-portfolio.netlify.app/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Web · Portfolio", "Web · Portfolio"),
      status: "Live",
      role: L("Frontend Developer", "Développeur frontend"),
      client: "Jennyfer",
      year: "2022",
      stack: ["HTML", "CSS", "Bootstrap"],
      features: [L("Personal website", "Site personnel")],
      more: L("Jennyfer's personal portfolio website.", "Le site portfolio personnel de Jennyfer."),
    },
  },
  {
    id: "facebookconnect",
    icon: "https://img.icons8.com/quill/50/facebook.png",
    bg: "#ffffff",
    label: "FB Connect",
    group: "Trainings",
    isLink: true,
    embed: true,
    url: "https://tranquil-fbconnect.netlify.app/",
    get content() { return appWindow(this); },
    properties: {
      category: L("Training · UI clone", "Formation · Clone UI"),
      status: "Training",
      role: L("Frontend Developer", "Développeur frontend"),
      year: "2023",
      stack: ["Vue JS"],
      features: [L("Facebook-like auth UI", "UI d'auth façon Facebook")],
      more: L("A Facebook-style connect / authentication UI experiment.", "Une expérimentation d'UI de connexion/authentification façon Facebook."),
    },
  },
  {
    id: "gocoachings",
    icon: "https://www.google.com/s2/favicons?sz=64&domain=gocoachings.com",
    bg: "#fff",
    label: "GoCoachings",
    isLink: true,
    embed: false,
    url: "https://www.gocoachings.com",
    get content() { return appWindow(this); },
    properties: {
      category: L("SaaS · Coaching", "SaaS · Coaching"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      team: STUDIO,
      year: "2023 — 2024",
      stack: ["Nuxt.js", "Strapi", "Node.js", "SCSS"],
      features: [L("Manage & measure coaching sessions", "Gérer & mesurer les séances de coaching"), L("All-in-one platform", "Plateforme tout-en-un")],
      more: L("The all-in-one platform to manage, monitor and measure your coaching sessions.", "La plateforme tout-en-un pour gérer, suivre et mesurer vos séances de coaching."),
    },
  },
  {
    id: "wapify",
    icon: "https://wapify.co/assets/img/logo.svg",
    bg: "#fff",
    label: "WAPIFY",
    isLink: true,
    embed: false,
    url: "https://wapify.co/",
    get content() { return appWindow(this); },
    properties: {
      category: L("SaaS · WhatsApp AI marketing", "SaaS · Marketing IA WhatsApp"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      team: STUDIO,
      year: "2023 — 2024",
      stack: ["Vue.js", "Laravel", "Python", "Node.js", "GPT AI", "Tailwind CSS"],
      features: [L("All-in-one WhatsApp marketing", "Marketing WhatsApp tout-en-un"), L("AI-assisted automation", "Automatisation assistée par IA")],
      more: L("The all-in-one, easy-to-use WhatsApp marketing AI tool to grow sales and qualify top clients.", "L'outil IA de marketing WhatsApp tout-en-un et simple pour booster les ventes et qualifier les meilleurs clients."),
    },
  },
  {
    id: "kloo",
    icon: "https://kloo.me/themes/altum/assets/images/customs/kloo.svg",
    bg: "#4062ff",
    label: "Kloo",
    isLink: true,
    embed: false,
    url: "https://kloo.me",
    get content() { return appWindow(this); },
    properties: {
      category: L("Web · Link-in-bio", "Web · Link-in-bio"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      team: "Fadel ABOU · Evans Uchwa",
      year: "2019",
      stack: ["PHP", "Bootstrap"],
      features: [L("Links & micro-pages", "Liens & micro-pages"), L("Bio-page enrichment", "Enrichissement de bio")],
      more: L("Boost engagement and traffic with links and micro-pages; enrich your bio pages.", "Boostez l'engagement et le trafic avec des liens et des micro-pages ; enrichissez vos pages de bio."),
    },
  },
  {
    id: "sevexchange",
    icon: sevexchange.src,
    label: "Sevexchange",
    isLink: true,
    embed: false,
    url: "https://sevexchange.com",
    get content() { return appWindow(this); },
    properties: {
      category: L("Fintech · Exchange", "Fintech · Échange"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      team: "Fadel ABOU · Evans Uchwa",
      year: "2019",
      stack: ["React", "Node.js"],
      features: [L("Crypto & mobile-money exchange", "Échange crypto & mobile money"), L("Secure transactions", "Transactions sécurisées")],
      more: L("Exchange your crypto and mobile-money currencies easily and securely.", "Échangez vos cryptos et vos devises mobile money facilement et en toute sécurité."),
    },
  },
  {
    id: "ninjalinking",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAAAPFBMVEVHcEz//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4P//4O5UZg5AAAAFHRSTlMARzoIEGxTmq4neMGCHozM/WC7606F424AAAETSURBVCiRdZJJgsQgCEURBRTneP+7NlZiuhbdrpTP+BDgPj5xESmcPHyfwJL7FePVs3D4taeSYyNSJm0xl3TsKNuMTv2cSBIFH3+7uupSSFArqrPnJyYUs8eT2FRTyn5yFgdvQQ8hupbZbhJJTznP26lSFA8pN8QTgH2Zr6OWE3DXWU+AjBZsVqTOUC56hTn67jQ4ugpIZKMgu3e/hm4iSTWKCWq1ZVwVriHh6cEES+UC1L6IxrpHrnOn4k5o3dJalggeQa24tUvOHnGMdSMPiLvdPWC11LzGfNjpZ0BD0jYqj+4JMFgbyQ0R0ksxHog3dsVaTU3G/2D/LEoI5/TqkKi9i3pWq8S6zV+r/f8z/PV9fgDxlAwONqjLlwAAAABJRU5ErkJggg==",
    label: "NinjaLinking",
    bg: "#333333",
    isLink: true,
    embed: false,
    url: "https://app.ninjalinking.fr",
    get content() { return appWindow(this); },
    properties: {
      category: L("SaaS · SEO backlinks", "SaaS · Backlinks SEO"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      team: STUDIO,
      year: "2024",
      stack: ["Vue.js", "Laravel", "Tailwind CSS"],
      features: [L("Backlink discovery", "Recherche de backlinks"), L("Referral link management", "Gestion des liens de référence")],
      more: L("Platform to find backlinks for your reference links.", "Plateforme pour trouver des backlinks vers vos liens de référence."),
    },
  },
  {
    id: "mdt",
    icon: "https://www.mdtfermetures.com/favicon.png",
    label: "Miroiterie du Ternois",
    bg: "#FFFFFF",
    isLink: true,
    embed: false,
    url: "https://www.mdtfermetures.com",
    get content() { return appWindow(this); },
    properties: {
      category: L("Business · Field management", "Business · Gestion terrain"),
      status: "Live",
      role: L("Full-Stack Developer", "Développeur full-stack"),
      team: STUDIO,
      year: "2025",
      stack: ["Vue.js", "Laravel", "Tailwind CSS"],
      features: [L("Worker & site management", "Gestion ouvriers & chantiers"), L("Job tracking", "Suivi des travaux")],
      more: L("Management of workers, sites and completed jobs.", "Gestion des ouvriers, des chantiers et des travaux effectués."),
    },
  },
];
